/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sue_protocol_SerialPortObserverThread */

#ifndef _Included_com_sue_protocol_SerialPortObserverThread
#define _Included_com_sue_protocol_SerialPortObserverThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sue_protocol_SerialPortObserverThread
 * Method:    initHandler
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_sue_protocol_SerialPortObserverThread_initHandler
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
