/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sue_usb_USBEventHandler */

#ifndef _Included_com_sue_usb_USBEventHandler
#define _Included_com_sue_usb_USBEventHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sue_usb_USBEventHandler
 * Method:    initHandler
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_sue_usb_USBEventHandler_initHandler
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
